"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Send,
  GitBranch,
  Code2,
  DollarSign,
  Shield,
  History,
  ChevronRight,
  Layers,
  Database,
  Globe,
  Server,
} from "lucide-react";

const chatMessages = [
  {
    role: "user",
    content:
      "SaaS app on AWS — Next.js, FastAPI, Postgres, Redis, ~5K users",
  },
  {
    role: "assistant",
    content:
      "I've designed a highly available architecture with the following components:\n\n- Application Load Balancer with SSL termination\n- Auto Scaling Group (2-10 instances)\n- RDS PostgreSQL Multi-AZ\n- S3 bucket with CloudFront CDN\n- VPC with public/private subnets\n\nCheck the tabs for diagrams, Terraform code, and cost analysis.",
  },
];

const historyItems = [
  { id: 1, title: "Scalable Web App", time: "2 min ago", active: true },
  { id: 2, title: "Microservices K8s", time: "1 hour ago", active: false },
  { id: 3, title: "Data Pipeline", time: "Yesterday", active: false },
  { id: 4, title: "Static Website", time: "2 days ago", active: false },
];

const terraformCode = `# Generated by InfraForge
# AWS Scalable Web Application

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "infraforge-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
}

resource "aws_lb" "main" {
  name               = "infraforge-alb"
  internal           = false
  load_balancer_type = "application"
  subnets            = module.vpc.public_subnets
}`;

export function WorkspacePreview() {
  const [inputValue, setInputValue] = useState("");

  return (
    <section id="workspace" className="px-6 py-20 md:py-32">
      <div className="mx-auto max-w-7xl">
        <div className="mb-12 text-center">
          <h2 className="text-balance text-3xl font-bold tracking-tight md:text-4xl">
            The Forge Workspace
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-pretty text-muted-foreground">
            A powerful, intuitive interface designed for DevOps engineers who value efficiency and precision.
          </p>
        </div>

        <Card className="overflow-hidden border-border/40 bg-card/30 backdrop-blur">
          <div className="flex h-[500px] md:h-[600px]">
            <div className="hidden w-64 border-r border-border/40 bg-secondary/30 lg:block">
              <div className="flex items-center gap-2 border-b border-border/40 px-4 py-3">
                <History className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm font-medium">History</span>
              </div>
              <ScrollArea className="h-[calc(100%-49px)]">
                <div className="p-2">
                  {historyItems.map((item) => (
                    <button
                      key={item.id}
                      className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors ${
                        item.active
                          ? "bg-primary/10 text-foreground"
                          : "text-muted-foreground hover:bg-secondary/50 hover:text-foreground"
                      }`}
                    >
                      <Layers className="h-4 w-4 shrink-0" />
                      <div className="min-w-0 flex-1">
                        <div className="truncate text-sm font-medium">{item.title}</div>
                        <div className="text-xs text-muted-foreground">{item.time}</div>
                      </div>
                      {item.active && <ChevronRight className="h-4 w-4 text-primary" />}
                    </button>
                  ))}
                </div>
              </ScrollArea>
            </div>

            <div className="flex flex-1 flex-col">
              <div className="flex-1 overflow-hidden">
                <div className="grid h-full md:grid-cols-2">
                  <div className="flex flex-col border-r border-border/40">
                    <ScrollArea className="flex-1 p-4">
                      <div className="space-y-4">
                        {chatMessages.map((msg, i) => (
                          <div
                            key={i}
                            className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                          >
                            <div
                              className={`max-w-[90%] rounded-lg px-4 py-3 ${
                                msg.role === "user"
                                  ? "bg-primary text-primary-foreground"
                                  : "bg-secondary text-secondary-foreground"
                              }`}
                            >
                              <p className="whitespace-pre-wrap text-sm">{msg.content}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </ScrollArea>
                    <div className="border-t border-border/40 p-4">
                      <div className="flex gap-2">
                        <input
                          type="text"
                          value={inputValue}
                          onChange={(e) => setInputValue(e.target.value)}
                          placeholder="Describe your infrastructure..."
                          className="flex-1 rounded-lg border border-border/60 bg-input px-4 py-2.5 text-sm placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                        />
                        <Button size="icon" className="shrink-0 bg-primary text-primary-foreground hover:bg-primary/90">
                          <Send className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  </div>

                  <div className="flex flex-col bg-secondary/20">
                    <Tabs defaultValue="diagram" className="flex h-full flex-col">
                      <TabsList className="h-auto w-full justify-start gap-0 rounded-none border-b border-border/40 bg-transparent p-0 overflow-x-auto">
                        <TabsTrigger
                          value="diagram"
                          className="gap-2 rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary data-[state=active]:bg-transparent"
                        >
                          <GitBranch className="h-4 w-4" />
                          <span className="hidden sm:inline">Diagram</span>
                        </TabsTrigger>
                        <TabsTrigger
                          value="terraform"
                          className="gap-2 rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary data-[state=active]:bg-transparent"
                        >
                          <Code2 className="h-4 w-4" />
                          <span className="hidden sm:inline">Terraform</span>
                        </TabsTrigger>
                        <TabsTrigger
                          value="cost"
                          className="gap-2 rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary data-[state=active]:bg-transparent"
                        >
                          <DollarSign className="h-4 w-4" />
                          <span className="hidden sm:inline">Cost</span>
                        </TabsTrigger>
                        <TabsTrigger
                          value="security"
                          className="gap-2 rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary data-[state=active]:bg-transparent"
                        >
                          <Shield className="h-4 w-4" />
                          <span className="hidden sm:inline">Security</span>
                        </TabsTrigger>
                      </TabsList>

                      <TabsContent value="diagram" className="m-0 flex-1 p-6">
                        <div className="flex h-full items-center justify-center">
                          <div className="flex flex-col items-center gap-4">
                            <div className="flex items-center gap-8">
                              <div className="flex flex-col items-center gap-2">
                                <div className="flex h-14 w-14 items-center justify-center rounded-lg border border-primary/40 bg-primary/10">
                                  <Globe className="h-6 w-6 text-primary" />
                                </div>
                                <span className="text-xs text-muted-foreground">ALB</span>
                              </div>
                              <div className="h-px w-8 bg-primary/40" />
                              <div className="flex flex-col items-center gap-2">
                                <div className="flex h-14 w-14 items-center justify-center rounded-lg border border-primary/40 bg-primary/10">
                                  <Server className="h-6 w-6 text-primary" />
                                </div>
                                <span className="text-xs text-muted-foreground">EC2 ASG</span>
                              </div>
                              <div className="h-px w-8 bg-primary/40" />
                              <div className="flex flex-col items-center gap-2">
                                <div className="flex h-14 w-14 items-center justify-center rounded-lg border border-primary/40 bg-primary/10">
                                  <Database className="h-6 w-6 text-primary" />
                                </div>
                                <span className="text-xs text-muted-foreground">RDS</span>
                              </div>
                            </div>
                            <p className="text-center text-sm text-muted-foreground">
                              Interactive Mermaid diagram
                            </p>
                          </div>
                        </div>
                      </TabsContent>

                      <TabsContent value="terraform" className="m-0 flex-1 overflow-hidden p-0">
                        <ScrollArea className="h-full">
                          <pre className="p-4 text-xs leading-relaxed">
                            <code className="text-muted-foreground">
                              {terraformCode.split("\n").map((line, i) => (
                                <div key={i} className="flex">
                                  <span className="mr-4 w-6 select-none text-right text-muted-foreground/50">
                                    {i + 1}
                                  </span>
                                  <span
                                    className={
                                      line.startsWith("#")
                                        ? "text-muted-foreground/70"
                                        : line.includes('"')
                                          ? "text-accent"
                                          : "text-foreground"
                                    }
                                  >
                                    {line || " "}
                                  </span>
                                </div>
                              ))}
                            </code>
                          </pre>
                        </ScrollArea>
                      </TabsContent>

                      <TabsContent value="cost" className="m-0 flex-1 p-6">
                        <div className="space-y-4">
                          <div className="text-center">
                            <div className="text-4xl font-bold text-primary">$847</div>
                            <div className="text-sm text-muted-foreground">Estimated monthly cost</div>
                          </div>
                          <div className="space-y-3">
                            {[
                              { name: "EC2 Instances", cost: "$420", percent: 50 },
                              { name: "RDS PostgreSQL", cost: "$285", percent: 34 },
                              { name: "Load Balancer", cost: "$82", percent: 10 },
                              { name: "S3 + CloudFront", cost: "$60", percent: 6 },
                            ].map((item) => (
                              <div key={item.name} className="space-y-1">
                                <div className="flex justify-between text-sm">
                                  <span className="text-muted-foreground">{item.name}</span>
                                  <span className="font-medium">{item.cost}</span>
                                </div>
                                <div className="h-2 overflow-hidden rounded-full bg-secondary">
                                  <div
                                    className="h-full rounded-full bg-primary"
                                    style={{ width: `${item.percent}%` }}
                                  />
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      </TabsContent>

                      <TabsContent value="security" className="m-0 flex-1 p-6">
                        <div className="space-y-4">
                          <div className="flex items-center gap-3">
                            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/20">
                              <Shield className="h-5 w-5 text-primary" />
                            </div>
                            <div>
                              <div className="font-medium">Security Score: 92/100</div>
                              <div className="text-sm text-muted-foreground">2 recommendations</div>
                            </div>
                          </div>
                          <div className="space-y-2">
                            {[
                              { status: "pass", text: "SSL/TLS termination enabled" },
                              { status: "pass", text: "Private subnets for databases" },
                              { status: "pass", text: "Security groups configured" },
                              { status: "warn", text: "Consider enabling WAF" },
                              { status: "warn", text: "Add CloudTrail logging" },
                            ].map((item, i) => (
                              <div key={i} className="flex items-center gap-2 text-sm">
                                <div
                                  className={`h-2 w-2 rounded-full ${
                                    item.status === "pass" ? "bg-primary" : "bg-yellow-500"
                                  }`}
                                />
                                <span className="text-muted-foreground">{item.text}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      </TabsContent>
                    </Tabs>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </section>
  );
}
